"""empty message

Revision ID: 01012acd186f
Revises: 37e643c93589
Create Date: 2021-04-08 02:29:24.924282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01012acd186f'
down_revision = '37e643c93589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'parent', 'person', ['own_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent', type_='foreignkey')
    # ### end Alembic commands ###
