"""empty message

Revision ID: 37e643c93589
Revises: 2607bda1e202
Create Date: 2021-04-08 02:27:48.366228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e643c93589'
down_revision = '2607bda1e202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('own_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'own_id')
    # ### end Alembic commands ###
